fix: make make_conninfo()'s first argument positional only
From commit c170851ab85f63935c0709ff0bfd7c1e7e9dd0c0, invoking
`conninfo.make_conninfo(**kwargs)` (with no 'conninfo' argument)
produces a typing (Mypy) error:

  error: Argument 1 to "make_conninfo" has incompatible type "**dict[str, str | int]"; expected "str"  [arg-type]

(here with `kwargs: dict[str, str | int]`).

Not specifying conninfo="", the default, is arguably a common pattern
and the only workaround on user side is to change the call to
make_conninfo("", **kwargs), which is quite cumbersome.

By making make_conninfo()'s conninfo argument positional only, the
typing error is resolved.

Added test serves as a non-regression, but mostly for typing.