Ignore (false) Mypy attr-defined error in dns tests
On test_dns*.py, Mypy raises:
    error: Module has no attribute "resolve_hostaddr_async" [attr-defined]
    error: Module has no attribute "resolve_srv" [attr-defined]

These are wrong since psycopg._dns actually has these names defined.
That's probably a mypy bug.